### ISSUE TITLE
Number of cal events hardcoded to 10

### ISSUE THREAD

**Issue by ammgws** [WnndGws/wallpaperMaker#13]
https://github.com/WnndGws/wallpaperMaker/blob/fb291bd02d32062b14193de70cc1439965d005a5/get_calendar_events.py#L59

Make it configurable? Some might only want 5.

**Comment by WnndGws** [comment]
This is done not because it limits the calendar events to 10.  What this function does is get the 10 next events in each of the user's calendar, and collates them into one list, then only keeps the events that are in the next two days. Ten was chosen as a (hopefully) large enough number so that we dont check too far in the future for calendars that have sparse entries, but will include all of the entries in a calendar that is used for day-to-day events

**Comment by ammgws** [comment]
OHK
